todo/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('add_task/', views.add_task, name='add_task'),
    path('remove_task/', views.remove_task, name='remove_task'),
    path('check_task/', views.check_task, name='check_task'),
    path('check_all_tasks/', views.check_all_tasks, name='check_all_tasks'),
    path('remove_all_tasks/', views.remove_all_tasks, name='remove_all_tasks'),
    path('remove_all_checked_tasks/', views.remove_all_checked_tasks, name='remove_all_checked_tasks'),
]

todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/core/models.py
from django.db import models


class Task(models.Model):
    task = models.CharField(null=False, blank=False, max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    checked = models.BooleanField(default=False)


class Todo(models.Model):
    task = models.ManyToManyField(Task)

todo/core/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render

from core.models import Todo, Task


def todo_list(request):
    try:
        todo_id = request.session['todo_id']
    except Exception:
        todo_id = None

    if todo_id:
        todo = Todo.objects.get(id=todo_id)
        tasks = todo.task.all().order_by('checked')
        tasks_all_checked = any(t.checked is False for t in tasks)
        context = {'todo': tasks, 'tac': tasks_all_checked}
    else:
        todo_empty = 'ToDo list is empty'
        context = {'empty': True, 'todo_empty': todo_empty}

    return render(request, 'index.html', context)


def add_task(request, *args, **kwargs):
    payload = {}

    try:
        todo_id = request.session['todo_id']
        payload['response'] = "Session is not empty."
    except Exception:
        new_todo = Todo()
        new_todo.save()
        request.session['todo_id'] = new_todo.id
        todo_id = new_todo.id
        payload['response'] = "Session todo_id created."

    todo = Todo.objects.get(id=todo_id)
    task_value = request.POST.get("task_value")

    if task_value != "":
        task = Task.objects.create(task=task_value)
        todo.task.add(task)
        payload['task_title'] = task.task
        payload['task_id'] = task.id
        payload['task_checked'] = task.checked
        payload['response'] = "Successfully added task."
    else:
        payload['response'] = 'Task can not be empty'
    return HttpResponse(json.dumps(payload), content_type="application/json")


def remove_task(request, *args, **kwargs):
    payload = {}

    try:
        request.session['todo_id']
    except Exception:
        new_todo = Todo()
        new_todo.save()
        request.session['todo_id'] = new_todo.id

    task_value = request.POST.get("task_id")

    if task_value != "":
        try:
            task = Task.objects.get(id=task_value)
            task.delete()
            payload['response'] = "Successfully removed task."
        except Task.DoesNotExist:
            payload['response'] = "Task already have been removed."
    else:
        payload['response'] = 'Task can not be empty.'

    return HttpResponse(json.dumps(payload), content_type="application/json")


def check_task(request, *args, **kwargs):
    payload = {}

    try:
        request.session['todo_id']
    except Exception:
        new_todo = Todo()
        new_todo.save()
        request.session['todo_id'] = new_todo.id

    task_value = request.POST.get("task_id")

    if task_value != "":
        try:
            task = Task.objects.get(id=task_value)
            if task.checked:
                task.checked = False
                task.save()
                payload['response'] = "Successfully ch task."
            else:
                task.checked = True
                task.save()
                payload['response'] = "Successfully ch task."
        except Task.DoesNotExist:
            payload['response'] = "Task already have been removed."
    else:
        payload['response'] = 'Task can not be empty.'

    return HttpResponse(json.dumps(payload), content_type="application/json")


def check_all_tasks(request, *args, **kwargs):
    payload = {}

    try:
        todo_id = request.session['todo_id']
    except Exception:
        new_todo = Todo()
        new_todo.save()
        request.session['todo_id'] = new_todo.id
        todo_id = new_todo.id

    todo = Todo.objects.get(id=todo_id)
    task_value = request.POST.get("tasks_checked")
    if task_value != "":
        tasks = todo.task.all()
        if tasks:
            if task_value == "checked":
                for task in tasks:
                    task.checked = False
                    task.save()
                payload['response'] = 'Successfully ch all task.'
            elif task_value == "unchecked":
                for task in tasks:
                    task.checked = True
                    task.save()
                payload['response'] = 'Successfully ch all task.'
        else:
            payload['response'] = "There is no task."
    else:
        payload['response'] = 'Task can not be empty.'

    return HttpResponse(json.dumps(payload), content_type="application/json")


def remove_all_tasks(request, *args, **kwargs):
    payload = {}

    try:
        todo_id = request.session['todo_id']
    except Exception:
        new_todo = Todo()
        new_todo.save()
        request.session['todo_id'] = new_todo.id
        todo_id = new_todo.id

    todo = Todo.objects.get(id=todo_id)

    tasks = todo.task.all()
    if tasks:
        tasks.delete()
        payload['response'] = 'Successfully removed all tasks.'
    else:
        payload['response'] = "There is no task."

    return HttpResponse(json.dumps(payload), content_type="application/json")


def remove_all_checked_tasks(request, *args, **kwargs):
    payload = {}

    try:
        todo_id = request.session['todo_id']
    except Exception:
        new_todo = Todo()
        new_todo.save()
        request.session['todo_id'] = new_todo.id
        todo_id = new_todo.id

    tasks = Task.objects.filter(todo__id=todo_id, checked=True)

    if tasks:
        tasks.delete()
        payload['response'] = 'Successfully removed all checked tasks.'
    else:
        payload['response'] = "There is no checked task."

    return HttpResponse(json.dumps(payload), content_type="application/json")

todo/templates/base.html
<!-- Write HTML code here -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>ToDo app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.3.0/font-awesome-animation.min.css"
          integrity="sha512-Po8rrCwchD03Wo+2ibHFielZ8luDAVoCyE9i6iFMPyn9+V1tIhGk5wl8iKC9/JfDah5Oe9nV8QzE8HHgjgzp3g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    {% endblock stylesheets %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fe49569996.js" crossorigin="anonymous"></script>
    {% endblock scripts %}

</head>
<body>
<div class="mt-5">
    <div class="container d-flex justify-content-center text-center">
        <a href="https://github.com/nijatrajab/todoapp" target="_blank" rel="noopener noreferrer">
            <button type="button" class="github-button faa-parent animated-hover">
                <i class="fab fa-github faa-tada"></i> Github Repo
            </button>
        </a>
    </div>
</div>

<div class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

todo/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}"/>
<script src="{% static 'assets/js/script.js' %}" type="text/javascript"></script>

<div class="new-task">
    <input class="form-control" type="text" placeholder="Enter new task" id="id_task_input">
    <button type="button" class="submit-task faa-parent animated-hover" onclick="addTask()" id="id_task_input_button">
        <i class="fas fa-plus faa-tada faa-fast"></i>
    </button>
</div>
<div class="container {% if todo %}all-buttons{% else %}all-buttons-hide{% endif %}" id="all_buttons">
    <button class="{% if tac %}check-all{% else %}uncheck-all{% endif %}" id="id_check_all" onclick="checkAll()">
        {% if tac %}Check all tasks{% else %}Uncheck all tasks{% endif %}
    </button>
    <button class="remove-all" id="id_remove_all" onclick="removeAll()">
        Remove all tasks
    </button>
    <button class="remove-all" id="id_remove_checked_all" onclick="removeAllChecked()">
        Remove checked tasks
    </button>
</div>
<div class="container" id="id_task_list">
    {% for i in todo %}
    <div class="todo-list" id="id_todo_{{i.id}}">
        <a class="task-list-item" id="id_task_item_{{i.id}}" {% if i.checked %}
           style="text-decoration-line: line-through" {% endif %}>{{i.task}}</a>
        <button class="{% if i.checked %}task-list-uncheck{% else %}task-list-check{% endif %} faa-parent animated-hover"
                type="button"
                id="id_task_check_{{i.id}}" onclick="checkTask('{{i.id}}', '{{i.task}}')">
            <i class="{% if i.checked %}fas fa-undo-alt faa-wrench faa-fast{% else %}fas fa-check faa-horizontal faa-reverse{% endif %}"></i>
        </button>
        <button class="task-list-remove faa-parent animated-hover" type="button"
                id="id_task_remove_{{i.id}}" onclick="removeTask('{{i.id}}')">
            <i class="far fa-trash-alt faa-flash faa-fast"></i>
        </button>
    </div>

    {% endfor %}
</div>

{% include 'snippets/add_task_js.html' %}
{% include 'snippets/remove_task_js.html' %}
{% include 'snippets/check_task_js.html' %}
{% include 'snippets/check_all_js.html' %}
{% include 'snippets/remove_all_js.html' %}
{% include 'snippets/remove_checked_all_js.html' %}

{% endblock %}

todo/templates/snippets/add_task_js.html
<script type="text/javascript">
    function addTask() {
        const taskValue = document.getElementById("id_task_input").value
        const allButton = document.getElementById("all_buttons")
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "task_value": taskValue
        }

        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url "core:add_task" %}',
            data: payload,
            timeout: 10000,
            success: function (data) {
                if (data.response == "Successfully added task.") {
                    taskItem(data.task_id, data.task_title, true, false)
                    document.getElementById("id_task_input").value = ""
                    allButton.classList.remove('all-buttons-hide')
                    allButton.classList.add('all-buttons')
                } else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function (data) {
                alert(data.response);
                // alert(jqXHR.status);
                // alert(textStatus);
                // alert(errorThrown);
            },

        })
    }
</script>

todo/templates/snippets/check_all_js.html
<script type="text/javascript">
    function checkAll() {
        const taskButtonsChecked = document.querySelectorAll(".task-list-check")

        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "tasks_checked": taskButtonsChecked.length === 0 ? "checked" : "unchecked"
        }

        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url "core:check_all_tasks" %}',
            data: payload,
            timeout: 10000,
            success: function (data) {
                if (data.response == "Successfully ch all task.") {
                    taskCheckAll()
                } else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        })
    }
</script>

todo/templates/snippets/check_task_js.html
<script type="text/javascript">
    function checkTask(taskID, taskTitle) {
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "task_id": taskID
        }

        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url "core:check_task" %}',
            data: payload,
            timeout: 10000,
            success: function (data) {
                if (data.response == "Successfully ch task.") {
                    taskCheckButton(taskID, taskTitle)
                } else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        })
    }
</script>

todo/templates/snippets/remove_all_js.html
<script type="text/javascript">
    function removeAll() {
        const allButton = document.getElementById("all_buttons")
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
        }

        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url "core:remove_all_tasks" %}',
            data: payload,
            timeout: 10000,
            success: function (data) {
                if (data.response == "Successfully removed all tasks.") {
                    taskRemoveAll()
                    allButton.classList.remove('all-buttons')
                    allButton.classList.add('all-buttons-hide')
                } else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        })
    }
</script>

todo/templates/snippets/remove_checked_all_js.html
<script type="text/javascript">
    function removeAllChecked() {
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
        }

        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url "core:remove_all_checked_tasks" %}',
            data: payload,
            timeout: 10000,
            success: function (data) {
                if (data.response == "Successfully removed all checked tasks.") {
                    taskRemoveAllChecked()
                } else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        })
    }
</script>

todo/templates/snippets/remove_task_js.html
<script type="text/javascript">
    function removeTask(taskID) {
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "task_id": taskID
        }

        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url "core:remove_task" %}',
            data: payload,
            timeout: 10000,
            success: function (data) {
                if (data.response == "Successfully removed task.") {
                    taskRemoveButton(taskID)
                } else if (data.response != null) {
                    alert(data.response)
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        })
    }
</script>